/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RevertsInterface extends utils.Interface {
  contractName: "Reverts";
  functions: {
    "requireWithMessage()": FunctionFragment;
    "requireWithoutMessage()": FunctionFragment;
    "revertWithCustomError()": FunctionFragment;
    "revertWithCustomErrorWithArgs()": FunctionFragment;
    "revertWithMessage()": FunctionFragment;
    "revertWithoutMessage()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "requireWithMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requireWithoutMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertWithCustomError",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertWithCustomErrorWithArgs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertWithMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertWithoutMessage",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "requireWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireWithoutMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertWithCustomError",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertWithCustomErrorWithArgs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertWithoutMessage",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Reverts extends BaseContract {
  contractName: "Reverts";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RevertsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    requireWithMessage(overrides?: CallOverrides): Promise<[void]>;

    requireWithoutMessage(overrides?: CallOverrides): Promise<[void]>;

    revertWithCustomError(overrides?: CallOverrides): Promise<[void]>;

    revertWithCustomErrorWithArgs(overrides?: CallOverrides): Promise<[void]>;

    revertWithMessage(overrides?: CallOverrides): Promise<[void]>;

    revertWithoutMessage(overrides?: CallOverrides): Promise<[void]>;
  };

  requireWithMessage(overrides?: CallOverrides): Promise<void>;

  requireWithoutMessage(overrides?: CallOverrides): Promise<void>;

  revertWithCustomError(overrides?: CallOverrides): Promise<void>;

  revertWithCustomErrorWithArgs(overrides?: CallOverrides): Promise<void>;

  revertWithMessage(overrides?: CallOverrides): Promise<void>;

  revertWithoutMessage(overrides?: CallOverrides): Promise<void>;

  callStatic: {
    requireWithMessage(overrides?: CallOverrides): Promise<void>;

    requireWithoutMessage(overrides?: CallOverrides): Promise<void>;

    revertWithCustomError(overrides?: CallOverrides): Promise<void>;

    revertWithCustomErrorWithArgs(overrides?: CallOverrides): Promise<void>;

    revertWithMessage(overrides?: CallOverrides): Promise<void>;

    revertWithoutMessage(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    requireWithMessage(overrides?: CallOverrides): Promise<BigNumber>;

    requireWithoutMessage(overrides?: CallOverrides): Promise<BigNumber>;

    revertWithCustomError(overrides?: CallOverrides): Promise<BigNumber>;

    revertWithCustomErrorWithArgs(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revertWithMessage(overrides?: CallOverrides): Promise<BigNumber>;

    revertWithoutMessage(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    requireWithMessage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requireWithoutMessage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revertWithCustomError(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revertWithCustomErrorWithArgs(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revertWithMessage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revertWithoutMessage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
